### ISSUE TITLE
Routing with https://openrouteservice.org/: traks saved are not correctly located 

### ISSUE THREAD

**Issue by MrDham** [strukturart/o.map#46]
Hi, 

Routing is a very great feature of o.map. However, it seems that there is a small bug when saving tracks.  

Step to reproduce

- Create a route e.g. from Limoges **(lat:45.8, lng1.2 )** to Poitier in France using method presented at https://www.reddit.com/r/KaiOS/comments/wl8yzb/omap_with_routing/. 
- Save it as Limoges-Poitier.geojson
- Open Limoges-Poitier.geojson

Expected result;  A track appears from Limoges to Poitier

Obtained result: A track appear in the sea at the south of Somalyia (somewhere around  **Lat:1.2, lng45.8** ) . 

It is just like latitude and longitude were swaped in the process. 

Best 
Vincent

**Comment by strukturart** [comment]
thank you for reporting the bug.

here you can find a version with which the bug is fixed. please try the version and tell me if the problem is solved.
https://github.com/strukturart/o.map/releases/tag/1.6

**new feature**
you can also use the markers menu (key *) to quickly change the profile (foot,cycling,car) of the routing request.

**Comment by MrDham** [comment]
It seem to be working perfectly now. Thank you for the fix. 

**New feature** : Very nice that we can change the profile quickly. :+1:
